export const String = {
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  password: "Password",
  phone: "Phone Number",
  login: "Login",
  signup: "Create Account",
  forgetPassword: "Forgot Password",
  confirmPassword: "Confirm Password",
  institute: "Enter Institute Name",
  uploadImage: "Upload ID Card Image ",
  verify: "Enter Verification Code",
  yearOfStudy: "Year Of Study",
  courseLength: "Course Length",
  submit: "Submit",
  revealCode: "Reveal Code",
  support: "Support",
  forumTitle: "Add Forum Title",
  forumDescription: "Add Forum Description",
  subscribe: "Subscribe",
  updateInfo:"Update Information",
  instituteName:"Institute Name",
  YrOfAdmisson:"Year Of Admission"
};
